In [1]:
import numpy as np
import matplotlib.pyplot as mpl
from sklearn.metrics import mean_squared_error

In [2]:
d = 100
n_train = 100
n_test = 100

x_train = np.random.randn(n_train, d)
x_test = np.random.randn(n_test, d)
mean_train = np.empty(d)
norm_tab = np.empty(n_train)

norm_train = (np.sum(x_train * x_train, axis = 1) ** 0.5).reshape(n_train, 1)
x_train = (x_train / norm_train) * (d ** 0.5)
    
norm_test = (np.sum(x_test * x_test, axis = 1) **0.5).reshape(n_test, 1)
x_test = (x_test / norm_test) * (d**0.5)

#On vérifie que notre data set soit uniforme (sur chaque dimension, le dataset a à peu près une moyenne de 0)
#On se rapproche de plus en plus de 0 lorsqu'on augmente n_train, les données étant mieux réparties
mean_train = np.sum(x_train, axis = 0) / n_train
    
#On vérifie que chaque élément de notre dataset ait une norme de sqrt(d)
norm_tab = np.sum(x_train * x_train, axis = 1) ** 0.5
    
print(x_train)
print(mean_train)
print(norm_tab)

[[ 0.55966322  1.91968871 -0.17764174 ...  0.27136752  0.10383974
  -1.13842675]
 [-1.53562404 -1.28052297  1.30303947 ...  0.70378453 -0.3563811
  -1.5376784 ]
 [ 1.03679244 -2.83290421 -1.6156227  ... -0.66153441  1.3240896
   0.99324659]
 ...
 [-1.05228301  0.6449208   0.881983   ... -0.13614209  0.32997485
  -0.41205993]
 [ 0.38517788  0.67230177  1.10773559 ...  0.10345264 -0.63418472
   0.99945811]
 [-1.01190348 -0.30861521 -0.60055545 ... -0.41960398 -0.42631601
  -1.42870796]]
[-0.13460775  0.02073274 -0.05123846 -0.03684429  0.06999158  0.02428018
 -0.01698616 -0.16808936 -0.12925297  0.03011144  0.03206035  0.22422625
 -0.02876989  0.08304679 -0.09237388  0.04244089 -0.08768415 -0.02061218
  0.12593252 -0.04465747 -0.20865592 -0.18546071 -0.08045186  0.0318762
  0.0672875   0.08386133  0.14002296  0.07206153  0.12305841 -0.00396065
  0.12790397 -0.04115929 -0.00978955  0.00663603  0.11648248 -0.09221591
  0.11825496  0.04870093  0.187799    0.10517194  0.16929694  0.01496919


In [3]:
tau = 0.3 
noise_level = tau * tau

#On veut E(noise) == 0 et E(noise^2) == tau^2
noise_train = np.random.randn(n_train, 1) * noise_level
noise_test = np.random.randn(n_test, 1) * noise_level

print(noise_train)

[[-0.12781377]
 [-0.03923029]
 [-0.07904442]
 [ 0.05741477]
 [-0.04845852]
 [ 0.01453979]
 [ 0.02755737]
 [-0.00175861]
 [ 0.07077686]
 [-0.07868615]
 [-0.04787398]
 [ 0.06709918]
 [-0.11015352]
 [ 0.1750214 ]
 [ 0.06575702]
 [-0.03954415]
 [-0.17609548]
 [ 0.07310113]
 [-0.06981979]
 [ 0.02879374]
 [-0.03039039]
 [-0.04331537]
 [ 0.00406155]
 [ 0.06411468]
 [-0.06498312]
 [-0.10635058]
 [ 0.02802123]
 [ 0.12020815]
 [ 0.09089286]
 [ 0.10570188]
 [-0.1241159 ]
 [ 0.04403384]
 [ 0.11180185]
 [ 0.10712743]
 [-0.00072577]
 [ 0.03498522]
 [-0.06701235]
 [ 0.04489236]
 [ 0.14139007]
 [-0.05461176]
 [-0.16959004]
 [-0.02545919]
 [ 0.13778267]
 [ 0.07950076]
 [-0.06812214]
 [ 0.03387911]
 [-0.04050964]
 [-0.03501495]
 [-0.04630265]
 [-0.14722693]
 [ 0.00259115]
 [-0.05154168]
 [-0.11665923]
 [ 0.12348315]
 [ 0.00347504]
 [-0.15107072]
 [ 0.09628691]
 [ 0.09206547]
 [-0.03401757]
 [-0.05117602]
 [ 0.06627562]
 [ 0.09326562]
 [ 0.16250485]
 [-0.03211107]
 [ 0.07912254]
 [ 0.04832567]
 [ 0.16078

In [4]:
F1 = 1

sample_params = np.random.randn(d, 1)
    
norm = np.sum(sample_params * sample_params) #should be equal to F1^2
sample_params = sample_params * (F1 / (norm**0.5))

print(sample_params)
print(np.sum(sample_params * sample_params) ** 0.5)

[[-0.08636917]
 [ 0.15059657]
 [-0.05041674]
 [ 0.02407247]
 [ 0.16721414]
 [ 0.08299572]
 [-0.14551764]
 [-0.12729818]
 [ 0.06843926]
 [-0.0448261 ]
 [-0.01633027]
 [ 0.10661415]
 [-0.12850346]
 [-0.16461718]
 [-0.14357349]
 [-0.0023188 ]
 [-0.15722676]
 [-0.08021234]
 [-0.04449533]
 [-0.07836209]
 [-0.1296414 ]
 [-0.03909144]
 [-0.02956377]
 [ 0.09196313]
 [ 0.08101829]
 [ 0.05375191]
 [-0.23507774]
 [ 0.13673358]
 [ 0.20639965]
 [ 0.11016033]
 [ 0.1252628 ]
 [-0.02816475]
 [-0.08193507]
 [-0.04297887]
 [-0.21678094]
 [ 0.04527932]
 [ 0.14240804]
 [-0.06522507]
 [ 0.07086588]
 [ 0.00645926]
 [-0.07099331]
 [ 0.13305495]
 [ 0.05992755]
 [-0.03894004]
 [-0.00073344]
 [ 0.07506835]
 [-0.06197657]
 [ 0.06728207]
 [-0.13543681]
 [ 0.03446349]
 [ 0.03527505]
 [ 0.01531769]
 [-0.0845779 ]
 [ 0.02764105]
 [ 0.05890864]
 [ 0.00118302]
 [ 0.05036781]
 [ 0.0336304 ]
 [ 0.06723106]
 [-0.0089023 ]
 [ 0.0592506 ]
 [-0.15458409]
 [ 0.02042158]
 [-0.02028615]
 [ 0.17068723]
 [ 0.02401497]
 [-0.20983

In [5]:
y_train = x_train @ sample_params + noise_train
y_test = x_test @ sample_params + noise_test
print(y_train)

[[ 1.31685713e+00]
 [ 1.61921551e+00]
 [-5.15564036e-01]
 [-7.86201766e-01]
 [-1.02264398e+00]
 [ 1.30527258e+00]
 [ 2.08673681e+00]
 [ 8.62651309e-01]
 [-8.00677185e-01]
 [-2.44123420e+00]
 [ 3.24313016e-01]
 [ 6.32396318e-01]
 [-1.27890868e+00]
 [-5.03502764e-01]
 [-8.16028202e-01]
 [-2.20471352e-01]
 [-1.10596696e-01]
 [ 1.00326067e+00]
 [-8.60210341e-02]
 [-5.11143033e-01]
 [ 8.06675411e-01]
 [ 1.94312574e+00]
 [ 2.03468569e+00]
 [-1.19107381e-01]
 [-1.26682466e+00]
 [-1.46961890e+00]
 [-4.06844054e-02]
 [-4.25729510e-01]
 [-6.21786764e-01]
 [-5.74683686e-01]
 [-6.61137467e-01]
 [ 1.41654547e+00]
 [ 3.97176465e-01]
 [-6.55314797e-01]
 [ 5.06083921e-01]
 [-1.50739650e+00]
 [-1.05832990e+00]
 [ 9.86420696e-01]
 [ 3.89657110e-01]
 [-1.69619043e-01]
 [ 2.39282986e-01]
 [ 1.53857057e+00]
 [ 5.61334710e-01]
 [ 1.48354139e+00]
 [ 6.85544726e-01]
 [-1.90777223e+00]
 [-1.29789706e+00]
 [ 7.61534928e-01]
 [-3.34122914e-01]
 [-5.94031014e-01]
 [-9.64121681e-01]
 [-1.08745849e+00]
 [ 3.1262499

In [6]:
#Quelques fonctions d'activation :

class Sigmoid :
    @staticmethod
    def function(x):
        return 1/(1+np.exp(-x))
    
    @staticmethod
    def gradient(x):
        s = Sigmoid.function(x)
        return s * (1- s)
    
class Tanh :
    @staticmethod
    def function(x):
        return np.tanh(x)
        
    @staticmethod
    def gradient(x):
        t = Tanh.function(x)
        return 1-t**2
    
class Relu :
    @staticmethod
    def function(x):
        return x * (x >= 0)
    
    @staticmethod
    def gradient(x):
        return x >= 0


In [7]:
#Quelques Loss Functions :
class MSE:
    @staticmethod
    def loss(y_real, y_hat):
        return (1/(y_real.shape[0] * y_real.shape[1])) * np.sum(np.sum((y_hat - y_real)**2, axis = 0))
    
    @staticmethod
    def gradient(y_real, y_hat):
        return (2/(y_real.shape[0] * y_real.shape[1])) * (y_hat - y_real)

In [8]:
#L'architecture

class Network:
    def __init__(self, dimension_hidden, activation1, activation2):
        """
        dimension_hidden est le nombre de paramètres dans le hidden layer (N dans le papier de Mei et Montanari)
        activation1 est la fonction d'activation du hidden layer
        activation2 est la fonction d'activation de l'output layer
        """
        
        self.nb_layers = 3 #input, hidden, output
        self.dimensions = (d, dimension_hidden, 1)
        
        self.loss_tab = None
        
        self.learning_rate = {}
        self.learning_rate[1] = None;  #learning rate du hidden layer
        self.learning_rate[2] = None;  #learning rate du output layer
        
        self.weights = {}
        self.bias = {}
        
        #on initialise les weights et les bias aléatoirement
        for i in range(self.nb_layers -1):
            self.weights[i + 1] = np.random.randn(self.dimensions[i], self.dimensions[i + 1]) / np.sqrt(self.dimensions[i])
            self.bias[i + 1] = np.zeros(self.dimensions[i + 1])
            
        self.activations = {}
        self.activations[2] = activation1
        self.activations[3] = activation2
        
    def forward_pass(self, x):
        """
        x est un vecteur de notre data
        """
        z = {}
        a = {1:x} #l'input layer n'a pas d'activation function, a[1] est donc égal à x
        
        for i in range(1, self.nb_layers):
            z[i + 1] = a[i] @ self.weights[i] + self.bias[i] #Z = XW + b
            a[i + 1] = self.activations[i + 1].function(z[i + 1]);
            
        return z, a
    
    def predict(self, x):
        z, a = self.forward_pass(x)
        return a[self.nb_layers]
    
    def back_propagation(self, z, a, real_value):
        y_hat = a[self.nb_layers]
        
        #On calcule delta et la dérivée partielle à l'output layer
        delta = self.loss_function.gradient(real_value, y_hat) * self.activations[self.nb_layers].gradient(y_hat)
        partial_deriv = a[self.nb_layers - 1].T @ delta
        
        update_parameters = {
            self.nb_layers - 1: (partial_deriv, delta)
        }
        
        for i in reversed(range(2, self.nb_layers)):
            delta = (delta @ self.weights[i].T) * self.activations[i].gradient(z[i])
            partial_deriv = a[i - 1].T @ delta 
            update_parameters[i - 1] = (partial_deriv, delta)
            
        for k, v in update_parameters.items():
            self.update_weights_and_bias(k, v[0], v[1])
            
    def update_weights_and_bias(self, index, partial_deriv, delta):
        self.weights[index] -= self.learning_rate[index] * partial_deriv
        self.bias[index] -= self.learning_rate[index] * np.mean(delta, 0)
        
    def fit(self, x, y_real, loss, nb_iterations, batch_size, learning_rate1, learning_rate2):
        #On vérifie qu'on a autant de x que de y
        if not (x.shape[0] == y_real.shape[0]):
            raise Exception
            
        self.loss_tab = np.empty((nb_iterations, x.shape[0] // batch_size))
        
        self.loss_function = loss
        self.learning_rate[1] = learning_rate1
        self.learning_rate[2] = learning_rate2
        
        #We use batch gradient descent
        for i in range(nb_iterations):
            for j in range(x.shape[0] // batch_size):
                start = j * batch_size
                end = (j + 1) * batch_size
                z, a = self.forward_pass(x[start:end])
                self.loss_tab[i][j] = self.loss_function.loss(y_real[start:end], a[self.nb_layers])
                self.back_propagation(z, a, y_real[start:end])
            if(i % 10) == 0:
                print("Loss at Iteration {} for first batch is {}".format(i, self.loss_tab[i][0]))
        

In [9]:
nn = Network(200, Sigmoid, Sigmoid)
nn.fit(x_train, y_train, MSE, 101, 10, 0, 0.03)

z, a = nn.forward_pass(x_test)
print(nn.loss_function.loss(y_test, a[nn.nb_layers]))

Loss at Iteration 0 for first batch is 2.133102808588878
Loss at Iteration 10 for first batch is 1.8701541651372027
Loss at Iteration 20 for first batch is 1.811810446895198
Loss at Iteration 30 for first batch is 1.7652767287492814
Loss at Iteration 40 for first batch is 1.7277852817870247
Loss at Iteration 50 for first batch is 1.6971355772525698
Loss at Iteration 60 for first batch is 1.6716851361399307
Loss at Iteration 70 for first batch is 1.6502364156784886
Loss at Iteration 80 for first batch is 1.6319192195408083
Loss at Iteration 90 for first batch is 1.6160955707780447
Loss at Iteration 100 for first batch is 1.6022901542375014
1.0706659940297758
